import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = (process.argv[2] === 'production');

// Sync to local vault if OBSIDIAN_VAULT_PATH env variable or default path is available
const VAULT_PLUGIN_DIR = process.env.OBSIDIAN_VAULT_PATH || "C:/Users/Ghelgen/Obsidian Vault's/Main/.obsidian/plugins/NEI-ai-chat";

function copyToVault() {
	try {
		if (VAULT_PLUGIN_DIR && fs.existsSync(VAULT_PLUGIN_DIR)) {
			if (fs.existsSync("main.js")) {
				fs.copyFileSync("main.js", path.join(VAULT_PLUGIN_DIR, "main.js"));
			}
			if (fs.existsSync("manifest.json")) {
				fs.copyFileSync("manifest.json", path.join(VAULT_PLUGIN_DIR, "manifest.json"));
			}
			if (fs.existsSync("styles.css")) {
				fs.copyFileSync("styles.css", path.join(VAULT_PLUGIN_DIR, "styles.css"));
			}
			console.log(`[esbuild] Successfully synced build files to Obsidian Vault: ${VAULT_PLUGIN_DIR}`);
		}
	} catch (e) {
		console.error("[esbuild] Error syncing build files to Vault:", e);
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: 'cjs',
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins: [{
		name: 'vault-sync',
		setup(build) {
			build.onEnd(result => {
				if (result.errors.length === 0) {
					copyToVault();
				}
			});
		}
	}]
});

if (prod) {
	await context.rebuild();
	copyToVault();
	process.exit(0);
} else {
	await context.watch();
}
